### ISSUE TITLE
Edit Time Log form breaks existing time log when editing

### ISSUE THREAD

**Issue by mddilley** [cityofaustin/atd-mobile-signals-work-orders#240] opened 2020-01-16 20:39 UTC
Jorge came by and showed us a bug where an existing `Time Log` resets to the current time when going through the editing process. The desired behavior is to populate the entire form with the existing record information, and then allow the user to edit the log. This test record also breaks the app when attempting to edit a time log (error below).

Also. change title of view from `New Time Log` to `Edit Time Log`.

Test record:
https://mobile-signals.mobility.austin.gov/work-order/5d77b278b4f2ca0012f620d3/edit-time-log/5d77b28b63f52c001282306c
### Broken app
<img width="1367" alt="Screen Shot 2020-01-16 at 2 33 40 PM" src="https://user-images.githubusercontent.com/37249039/72560869-87d9a580-386d-11ea-86cd-9527779e7160.png">

**Comment by mateoclarke** [comment] 2020-01-21 20:24
duplicate of https://github.com/cityofaustin/atd-data-tech/issues/1217

**Closed by mateoclarke** 2020-01-21 20:24 UTC
Labels: Duplicate, Project: Mobile Signal Work Order, Service: Dev, Type: Bug Report, Workgroup: AMD
